apiVersion: v1
kind: Pod
metadata:
  name: mlprod-pod-resources
  labels:
    app: mlprod-pod-resources
spec:
  containers:
    - image: polonium13/online_inference_model:v2
      name: mlprod
      ports:
        - containerPort: 8000
      resources:
        requests:
            memory: "50Mi"
            cpu: 1
        limits:
            memory: "500Mi"
            cpu: 2